### ISSUE TITLE
I was never asked for encryption keys

### ISSUE THREAD

**Issue by drnic** [genesis-community/hashistack-genesis-kit#2]
README says:

```
When it asks for the encryption keys to consul / nomad you can generate them with:

$ consul keygen
Rt1ueEJfsdesOKbFJ3vduw==
```

I was not prompted for this. Can it be removed from README; or did I do something wrong in my preparation?

**Comment by bodymindarts** [comment]
Sorry docs are outdated. Latest release takes care of it automatically.
